dependencies: []
#  - name: redis
#    version: "~1.1" # Please check version
#    repository: "https://jobteaser.github.io/charts"
#    condition: redis.enabled

#  - name: mysql
#    version: "~1.0" # Please check version
#    repository: "https://jobteaser.github.io/charts"
#    condition: mysql.enabled

#  - name: elasticsearch
#    version: "~2.0" # Please check version
#    repository: "https://jobteaser.github.io/charts"
#    condition: elasticsearch.enabled