apiVersion: v1
kind: Service
metadata:
  name: {{ template "__CHART__.fullname" . }}
  labels:
    app: {{ template "__CHART__.name" . }}
    chart: {{ template "__CHART__.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "__CHART__.name" . }}
    release: {{ .Release.Name }}
